version: 2
jobs:
  build:
    working_directory: ~/Desktop/sollento/sollentoCirlceCI/sollentomarket
    docker:
      - image: circleci/php:7.2.4-apache-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: Composer
          command: sudo composer self-update
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Run tests
          command: vendor/phpunit/phpunit/phpunit